import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../theme/app_colors.dart';
import '../../../core/providers.dart';
import '../../../models/user_model.dart';
import '../../../models/support_ticket_model.dart';
import '../../../services/support_service.dart';

class CreateTicketScreen extends ConsumerStatefulWidget {
  final String? initialCategory;
  const CreateTicketScreen({super.key, this.initialCategory});

  @override
  ConsumerState<CreateTicketScreen> createState() => _CreateTicketScreenState();
}

class _CreateTicketScreenState extends ConsumerState<CreateTicketScreen> {
  final _formKey = GlobalKey<FormState>();
  late String _selectedCategory;
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  TicketPriority _priority = TicketPriority.medium;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _selectedCategory = widget.initialCategory ?? 'Other';
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _submitTicket() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    final user = ref.read(userModelProvider).asData?.value;
    if (user == null) return;

    final ticket = SupportTicketModel(
      id: '', // Will be generated by Firestore
      userId: user.uid,
      userName: user.name,
      userRole: user.role,
      category: _selectedCategory,
      title: _titleController.text.trim(),
      description: _descriptionController.text.trim(),
      status: TicketStatus.open,
      priority: _priority,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    try {
      final ticketId = await ref.read(supportServiceProvider).createTicket(ticket);
      
      // Send initial message
      await ref.read(supportServiceProvider).sendMessage(ticketId, SupportMessageModel(
        id: '',
        senderId: user.uid,
        senderName: user.name,
        senderRole: user.role.name,
        message: _descriptionController.text.trim(),
        timestamp: DateTime.now(),
      ));

      if (mounted) {
        context.pop();
        context.push('/support/ticket-chat/$ticketId');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating ticket: $e'), backgroundColor: AppColors.error),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final user = ref.watch(userModelProvider).asData?.value;
    final categories = _getCategoriesForRole(user?.role ?? UserRole.customer);
    
    final theme = Theme.of(context);
    final isLight = theme.brightness == Brightness.light;
    
    final bgColor = isLight ? AppColors.lightBackground : AppColors.supportDarkBackground;
    final cardColor = isLight ? AppColors.lightSurface : AppColors.supportDarkSurface;
    final primaryColor = isLight ? AppColors.lightPrimary : AppColors.supportDarkPrimary;
    final textColor = isLight ? AppColors.lightTextPrimary : AppColors.supportDarkTextPrimary;
    final secondaryTextColor = isLight ? AppColors.lightTextSecondary : AppColors.supportDarkTextSecondary;
    final dividerColor = isLight ? AppColors.lightBorder : AppColors.supportDarkDivider;

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        title: Text('Create New Ticket', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18, color: textColor)),
        backgroundColor: bgColor,
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: Icon(Icons.close_rounded, color: textColor),
          onPressed: () => context.pop(),
        ),
      ),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('ISSUE CATEGORY', primaryColor),
              const SizedBox(height: 12),
              _buildDropdown(categories, cardColor, textColor, dividerColor),
              
              const SizedBox(height: 32),
              _buildSectionTitle('PRIORITY LEVEL', primaryColor),
              const SizedBox(height: 12),
              _buildPrioritySelector(primaryColor, cardColor, textColor, dividerColor),
              
              const SizedBox(height: 32),
              _buildSectionTitle('SUBJECT', primaryColor),
              const SizedBox(height: 12),
              _buildTextField(
                controller: _titleController,
                hint: 'Briefly describe your issue',
                cardColor: cardColor,
                textColor: textColor,
                dividerColor: dividerColor,
                secondaryTextColor: secondaryTextColor,
              ),
              
              const SizedBox(height: 32),
              _buildSectionTitle('DESCRIPTION', primaryColor),
              const SizedBox(height: 12),
              _buildTextField(
                controller: _descriptionController,
                hint: 'Provide as much detail as possible so we can help you faster...',
                maxLines: 6,
                cardColor: cardColor,
                textColor: textColor,
                dividerColor: dividerColor,
                secondaryTextColor: secondaryTextColor,
              ),
              
              const SizedBox(height: 48),
              ElevatedButton(
                onPressed: _isLoading ? null : _submitTicket,
                style: ElevatedButton.styleFrom(
                  backgroundColor: primaryColor,
                  foregroundColor: Colors.white,
                  minimumSize: const Size(double.infinity, 60),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                  elevation: 8,
                  shadowColor: primaryColor.withOpacity(0.4),
                ),
                child: _isLoading 
                  ? const SizedBox(height: 24, width: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 3))
                  : const Text('SUBMIT TICKET', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w900, letterSpacing: 1.5)),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title, Color color) {
    return Text(
      title,
      style: TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: color, letterSpacing: 2),
    );
  }

  Widget _buildDropdown(List<String> categories, Color cardColor, Color textColor, Color divider) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: divider),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButtonFormField<String>(
          value: categories.contains(_selectedCategory) ? _selectedCategory : categories.last,
          dropdownColor: cardColor,
          icon: Icon(Icons.keyboard_arrow_down_rounded, color: textColor.withOpacity(0.5)),
          items: categories.map((c) => DropdownMenuItem(
            value: c, 
            child: Text(c, style: TextStyle(color: textColor, fontWeight: FontWeight.w600, fontSize: 15))
          )).toList(),
          onChanged: (val) => setState(() => _selectedCategory = val!),
          decoration: const InputDecoration(border: InputBorder.none),
        ),
      ),
    );
  }

  Widget _buildPrioritySelector(Color primary, Color cardColor, Color textColor, Color divider) {
    return Row(
      children: TicketPriority.values.map((p) {
        final isSelected = _priority == p;
        return Expanded(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 4),
            child: InkWell(
              onTap: () => setState(() => _priority = p),
              borderRadius: BorderRadius.circular(12),
              child: Container(
                padding: const EdgeInsets.symmetric(vertical: 12),
                decoration: BoxDecoration(
                  color: isSelected ? primary : cardColor,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: isSelected ? primary : divider),
                ),
                child: Center(
                  child: Text(
                    p.name.toUpperCase(),
                    style: TextStyle(
                      color: isSelected ? Colors.white : textColor.withOpacity(0.6),
                      fontWeight: FontWeight.w900,
                      fontSize: 11,
                      letterSpacing: 0.5,
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    int maxLines = 1,
    required Color cardColor,
    required Color textColor,
    required Color dividerColor,
    required Color secondaryTextColor,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: dividerColor),
      ),
      child: TextFormField(
        controller: controller,
        maxLines: maxLines,
        style: TextStyle(color: textColor, fontWeight: FontWeight.w600, fontSize: 15),
        validator: (val) => val!.isEmpty ? 'Field required' : null,
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: TextStyle(color: secondaryTextColor.withOpacity(0.4), fontWeight: FontWeight.w500, fontSize: 14),
          contentPadding: const EdgeInsets.all(16),
          border: InputBorder.none,
        ),
      ),
    );
  }

  List<String> _getCategoriesForRole(UserRole role) {
    switch (role) {
      case UserRole.customer:
        return ['Order Issue', 'Payment', 'Refund', 'Delivery', 'Product Quality', 'Technical', 'Other'];
      case UserRole.vendor:
        return ['Shop Verification', 'Product Approval', 'Payment', 'Withdrawal', 'Technical', 'Customer Complaint', 'Other'];
      case UserRole.rider:
        return ['Delivery Problem', 'Wrong Address', 'Customer Not Available', 'Vehicle Issue', 'Earnings', 'Withdrawal', 'Technical'];
      default:
        return ['General Support', 'Technical Issue', 'Other'];
    }
  }
}
