// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtEzfcDlX3GGNrQdAC2pkOYsZRPhtX6LM',
    appId: '1:262483790491:web:9ff1d05b1444181057d43e',
    messagingSenderId: '262483790491',
    projectId: 'rooz-stor',
    authDomain: 'rooz-stor.firebaseapp.com',
    storageBucket: 'rooz-stor.firebasestorage.app',
    measurementId: 'G-Z65XJ0SWE4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZxHqv9-jXb5JUSUQ-BeUoraOfdjWieds',
    appId: '1:262483790491:ios:d0a0d70a1d3285ba57d43e',
    messagingSenderId: '262483790491',
    projectId: 'rooz-stor',
    storageBucket: 'rooz-stor.firebasestorage.app',
    iosBundleId: 'com.example.zenMartPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtEzfcDlX3GGNrQdAC2pkOYsZRPhtX6LM',
    appId: '1:262483790491:web:60ad4d6fb26494aa57d43e',
    messagingSenderId: '262483790491',
    projectId: 'rooz-stor',
    authDomain: 'rooz-stor.firebaseapp.com',
    storageBucket: 'rooz-stor.firebasestorage.app',
    measurementId: 'G-H4YK0EH27T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZxHqv9-jXb5JUSUQ-BeUoraOfdjWieds',
    appId: '1:262483790491:ios:c51dabacd13b8ec757d43e',
    messagingSenderId: '262483790491',
    projectId: 'rooz-stor',
    storageBucket: 'rooz-stor.firebasestorage.app',
    iosBundleId: 'com.rooz.store',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-2SUhVW-QsWYlo9Qcm2Olk8KOZY80q4',
    appId: '1:262483790491:android:186249fcc38c612657d43e',
    messagingSenderId: '262483790491',
    projectId: 'rooz-stor',
    storageBucket: 'rooz-stor.firebasestorage.app',
    androidClientId: '262483790491-3u8l84225b0e9ms8rg41v8sdgknabh9i.apps.googleusercontent.com',
  );
}