import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'settings_provider.dart';

class Localization {
  final String locale;
  Localization(this.locale);

  static const _en = {
    'my_profile': 'My Profile',
    'total_orders': 'Total Orders',
    'wishlist': 'Wishlist',
    'account_settings': 'Account Settings',
    'edit_profile': 'Edit Profile',
    'saved_addresses': 'Saved Addresses',
    'change_password': 'Change Password',
    'my_activity': 'My Activity',
    'order_history': 'Order History',
    'wishlist_items': 'Wishlist Items',
    'notifications': 'Notifications',
    'preferences': 'Preferences',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'sign_out': 'Sign Out',
    'edit_profile_title': 'Edit Profile',
    'full_name': 'Full Name',
    'phone_number': 'Phone Number',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'select_language': 'Select Language',
    'urdu': 'Urdu (اردو)',
    'english': 'English',
    'upload_picture': 'Upload Picture',
    'no_notifications': 'No notifications yet',
    'deliver_to': 'Deliver to',
    'search_hint': 'Search for food, grocery...',
    'what_buy': 'What would you like to buy?',
    'featured_stores': 'Featured Stores',
    'view_all': 'View All',
    'popular_near': 'Popular Near You',
    'grocery': 'Grocery',
    'food': 'Food',
    'pharmacy': 'Pharmacy',
    'fashion': 'Fashion',
    'item_total': 'Item Total',
    'delivery_fee': 'Delivery Fee',
    'taxes': 'Taxes',
    'grand_total': 'Grand Total',
    'checkout': 'Proceed to Checkout',
    'my_cart': 'My Cart',
    'clear': 'Clear',
    'empty_cart': 'Your cart is empty',
    'start_shopping': 'Start Shopping',
    'confirm_order': 'Confirm Order',
    'delivery_location': 'Delivery Location',
    'payment_method': 'Payment Method',
    'order_items': 'Order Items',
    'cash_on_delivery': 'Cash on Delivery',
    'online_transfer': 'Online Transfer',
    'pay_confirm': 'Pay & Confirm Order',
    'order_summary': 'Order Summary',
    'item_subtotal': 'Order Subtotal',
    'total_to_pay': 'Total to Pay',
    'select_address': 'Select Address',
    'add_address_hint': 'Please add a delivery address to continue',
    'product_details': 'Product Details',
    'by': 'by',
    'description': 'Description',
    'reviews': 'Reviews',
    'customer_reviews': 'Customer Reviews',
    'no_reviews': 'No reviews yet',
    'ordered': 'ordered',
    'times': 'times',
    'in_stock': 'In Stock',
    'low_stock': 'Low Stock',
    'add_to_bag': 'Add to Bag',
    'buy_now': 'Buy Now',
    'items_left': 'items left',
    'ready_ship': 'Ready for immediate premium delivery',
    'home': 'Home',
    'search': 'Search',
    'cart': 'Cart',
    'orders': 'Orders',
    'account': 'Account',
    'my_wishlist': 'My Wishlist',
    'empty_wishlist': 'Your wishlist is empty',
    'wishlist_hint': 'Explore products and save your favorites!',
    'explore_now': 'Explore Now',
    'support_hub': 'Support Hub',
    'quick_help': 'Quick Help',
    'live_chat': 'Live Chat Support',
    'chat_now': 'Chat with our support experts now.',
    'start': 'START',
    'emergency_help': 'Emergency Assistance',
    'safety_fraud': 'Safety issues or fraud report.',
    'my_tickets': 'My Tickets',
    'common_questions': 'Common Questions',
    'new_ticket': 'NEW TICKET',
    'live_online': 'LIVE SUPPORT ONLINE',
    'how_help': 'How can we help you today?',
    'search_support_hint': 'Search FAQs, tickets or articles...',
    'order_issue': 'Order Issue',
    'refund_issue': 'Refund',
    'payment_issue': 'Payment',
    'delivery_issue': 'Delivery',
    'quality_issue': 'Product Quality',
    'technical_issue': 'Technical',
    'other_issue': 'Other',
    'urgent': 'URGENT',
    'status': 'Status',
    'last_updated': 'Last updated',
    'avg_reply': 'Avg. reply: 2 min',
    'no_tickets': 'No active tickets found.',
    'Hi': 'Hi',
  };

  static const _ur = {
    'my_profile': 'میری پروفائل',
    'total_orders': 'کل آرڈرز',
    'wishlist': 'خواہش کی فہرست',
    'account_settings': 'اکاؤنٹ کی ترتیبات',
    'edit_profile': 'پروفائل تبدیل کریں',
    'saved_addresses': 'محفوظ کردہ پتے',
    'change_password': 'پاس ورڈ تبدیل کریں',
    'my_activity': 'میری سرگرمی',
    'order_history': 'آرڈر کی تاریخ',
    'wishlist_items': 'خواہش کی فہرست کی اشیاء',
    'notifications': 'اطلاعات',
    'preferences': 'ترجیحات',
    'dark_mode': 'ڈارک موڈ',
    'language': 'زبان',
    'sign_out': 'سائن آؤٹ',
    'edit_profile_title': 'پروفائل میں ترمیم کریں',
    'full_name': 'پورا نام',
    'phone_number': 'فون نمبر',
    'cancel': 'منسوخ کریں',
    'save_changes': 'تبدیلیاں محفوظ کریں',
    'select_language': 'زبان منتخب کریں',
    'urdu': 'اردو',
    'english': 'انگریزی',
    'upload_picture': 'تصویر اپ لوڈ کریں',
    'no_notifications': 'ابھی تک کوئی اطلاع نہیں ہے',
    'deliver_to': 'ڈیلیور کریں',
    'search_hint': 'کھانے، گروسری تلاش کریں...',
    'what_buy': 'آپ کیا خریدنا چاہیں گے؟',
    'featured_stores': 'نمایاں اسٹورز',
    'view_all': 'سب دیکھیں',
    'popular_near': 'آپ کے قریب مقبول',
    'grocery': 'گروسری',
    'food': 'کھانا',
    'pharmacy': 'فارماسی',
    'fashion': 'فیشن',
    'item_total': 'آئٹم ٹوٹل',
    'delivery_fee': 'ڈیلیوری فیس',
    'taxes': 'ٹیکس',
    'grand_total': 'کل رقم',
    'checkout': 'چیک آؤٹ کریں',
    'my_cart': 'میری کارٹ',
    'clear': 'صاف کریں',
    'empty_cart': 'آپ کی ٹوکری خالی ہے',
    'start_shopping': 'خریداری شروع کریں',
    'confirm_order': 'آرڈر کی تصدیق کریں',
    'delivery_location': 'ڈیلیوری کا مقام',
    'payment_method': 'ادائیگی کا طریقہ',
    'order_items': 'آرڈر کی اشیاء',
    'cash_on_delivery': 'کیش آن ڈیلیوری',
    'online_transfer': 'آن لائن ٹرانسفر',
    'pay_confirm': 'ادائیگی اور آرڈر کی تصدیق کریں',
    'order_summary': 'آرڈر کا خلاصہ',
    'item_subtotal': 'سب ٹوٹل',
    'total_to_pay': 'کل قابل ادائیگی',
    'select_address': 'پتہ منتخب کریں',
    'add_address_hint': 'جاری رکھنے کے لیے براہ کرم ڈیلیوری کا پتہ شامل کریں',
    'product_details': 'مصنوعات کی تفصیلات',
    'by': 'کی طرف سے',
    'description': 'تفصیل',
    'reviews': 'جائزے',
    'customer_reviews': 'صارفین کے جائزے',
    'no_reviews': 'ابھی تک کوئی جائزہ نہیں ہے',
    'ordered': 'آرڈر کیا گیا',
    'times': 'بار',
    'in_stock': 'اسٹاک میں ہے',
    'low_stock': 'اسٹاک کم ہے',
    'add_to_bag': 'بیگ میں شامل کریں',
    'buy_now': 'ابھی خریدیں',
    'items_left': 'اشیاء باقی ہیں',
    'ready_ship': 'فوری طور پر ڈیلیوری کے لیے تیار ہے',
    'home': 'ہوم',
    'search': 'تلاش',
    'cart': 'کارٹ',
    'orders': 'آرڈرز',
    'account': 'اکاؤنٹ',
    'my_wishlist': 'میری خواہش کی فہرست',
    'empty_wishlist': 'آپ کی خواہش کی فہرست خالی ہے',
    'wishlist_hint': 'مصنوعات تلاش کریں اور اپنے پسندیدہ کو محفوظ کریں!',
    'explore_now': 'ابھی دریافت کریں',
    'support_hub': 'سپورٹ مرکز',
    'quick_help': 'فوری مدد',
    'live_chat': 'لائیو چیٹ سپورٹ',
    'chat_now': 'ابھی ہمارے سپورٹ ماہرین سے چیٹ کریں۔',
    'start': 'شروع کریں',
    'emergency_help': 'ہنگامی مدد',
    'safety_fraud': 'حفاظتی مسائل یا دھوکہ دہی کی رپورٹ۔',
    'my_tickets': 'میرے ٹکٹ',
    'common_questions': 'عام سوالات',
    'new_ticket': 'نیا ٹکٹ',
    'live_online': 'لائیو سپورٹ آن لائن',
    'how_help': 'آج ہم آپ کی کیا مدد کر سکتے ہیں؟',
    'search_support_hint': 'سوالات، ٹکٹ یا مضامین تلاش کریں...',
    'order_issue': 'آرڈر کا مسئلہ',
    'refund_issue': 'رقم کی واپسی',
    'payment_issue': 'ادائیگی',
    'delivery_issue': 'ڈیلیوری',
    'quality_issue': 'مصنوعات کا معیار',
    'technical_issue': 'تکنیکی',
    'other_issue': 'دیگر',
    'urgent': 'فوری',
    'status': 'حیثیت',
    'last_updated': 'آخری بار اپ ڈیٹ کیا گیا',
    'avg_reply': 'اوسط جواب: 2 منٹ',
    'no_tickets': 'کوئی فعال ٹکٹ نہیں ملا۔',
    'Hi': 'ہیلو',
  };

  String translate(String key) {
    if (locale == 'ur') {
      return _ur[key] ?? key;
    }
    return _en[key] ?? key;
  }
}

final localizationProvider = Provider<Localization>((ref) {
  final settings = ref.watch(settingsProvider);
  return Localization(settings.locale.languageCode);
});

extension Trans on String {
  String tr(WidgetRef ref) {
    return ref.watch(localizationProvider).translate(this);
  }
}
